name: webdesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23793
title: Webspiration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f7ee'
    - '#a54a3c'
    - '#eabeae'
    - '#41283a'
    - '#9fa09f'
  brandStrength: 0.64534519193694
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
